name: "Scan for Evil Packages"
description: "Scans a repository for compromised packages across all branches."
inputs:
  slack-webhook-url:
    description: "Slack Webhook URL for notifications"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Clone hof-vulnerabilities-scanner
      run: git clone https://github.com/UKHomeOfficeForms/hof-vulnerabilities-scanner.git
      shell: bash

    - name: Run vulnerability scan
      run: |
        set -euo pipefail
        summary=""
        any_compromised=0
        repo_name=$(basename "$GITHUB_REPOSITORY")
        git checkout main 2>/dev/null || git checkout master
        node hof-vulnerabilities-scanner/index.js --out "scan-results.json" || true
        cnt=$(jq '.meta.vulnerabilitiesCount // 0' "$GITHUB_WORKSPACE/scan-results.json" 2>/dev/null || echo 0)
        if [ "$cnt" -gt 0 ]; then
          any_compromised=1
          summary="${cnt} compromised package(s)"
        fi

        if [ "$any_compromised" -eq 0 ]; then
          final="$repo_name: No compromised packages found. ✅"
        else
          final="$repo_name: ${summary} found (See Github action logs for further details). ❌"
        fi

        echo -e "$final" > summary.txt
        echo "SUMMARY_FILE=summary.txt" >> $GITHUB_ENV
      shell: bash

    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
      run: |
        text=$(cat "$SUMMARY_FILE")
        payload=$(jq -Rs '{text: .}' < "$SUMMARY_FILE")
        curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
      shell: bash
