name: "Scan for Evil Packages"
description: "Scans a repository for compromised packages across all branches."
inputs:
  slack-webhook-url:
    description: "Slack Webhook URL for notifications"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Clone hof-vulnerabilities-scanner
      run: git clone https://github.com/UKHomeOfficeForms/hof-vulnerabilities-scanner.git
      shell: bash

    - name: Run vulnerability scan
      run: |
        set -euo pipefail
        echo "\n============================================"
        echo "🔎 Starting Evil Package Scan"
        echo "📦 Repository: $GITHUB_REPOSITORY"
        echo "============================================\n"

        git fetch --all --prune
        branches=$(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||')
        summary=""
        any_compromised=0
        repo_name=$(basename "$GITHUB_REPOSITORY")

        echo "::group::🌿 Branch Scans"
        for br in $branches; do
          echo "\n--------------------------------------------"
          echo "🌿 Scanning branch: $br"
          echo "--------------------------------------------"
          git checkout --force -B "$br" "origin/$br"
          node hof-vulnerabilities-scanner/index.js --out "scan-results-${br}.json" || true
          cnt=$(jq '.vulnerabilitiesCount // 0' "scan-results-${br}.json" 2>/dev/null || echo 0)
          if [ "$cnt" -gt 0 ]; then
            any_compromised=1
            echo "⚠️  Found $cnt compromised packages on $br"
            summary="${summary}${br}: ${cnt} compromised packages\n"
          else
            echo "✅ No compromised packages on $br"
            summary="${summary}${br}: 0\n"
          fi
          echo "🗂️  Results file: scan-results-${br}.json"
        done
        echo "::endgroup::"

        echo "\n============================================"
        echo "📊 Scan Summary"
        echo "============================================"
        printf "%b" "$summary"

        if [ "$any_compromised" -eq 0 ]; then
          final="$repo_name: No compromised packages found. ✅"
        else
          final="$repo_name: Compromised packages found:\n${summary} ❌"
        fi

        echo "\n🧾 Message to Slack:"
        printf "%b\n" "$final"
        echo "summary=$final" >> $GITHUB_ENV
      shell: bash

    - name: Notify to Slack
      run: |
        echo "\n📣 Preparing to notify Slack..."
        echo "Webhook: ${SLACK_WEBHOOK_URL:+(set)}${SLACK_WEBHOOK_URL:-(not set)}"
        echo "Preview message:"
        printf "%b\n" "${summary:-$SCAN_OUTPUT}"
      shell: bash

    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        SCAN_OUTPUT: ${{ env.summary }}
      run: |
        echo "\n🚀 Sending Slack notification..."
        payload=$(jq -n --arg text "$SCAN_OUTPUT" '{text: $text}')
        echo "Payload:" && echo "$payload"
        curl -s -o /tmp/slack_resp.txt -w "status:%{http_code}\n" -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
        status_line=$(tail -n1 /tmp/slack_resp.txt)
        if echo "$status_line" | grep -q "status:200"; then
          echo "✅ Slack notified successfully"
        else
          echo "❌ Slack notification failed ($status_line)"
          echo "Response body:" && sed '$d' /tmp/slack_resp.txt || true
        fi
      shell: bash
