name: "Scan for Evil Packages"
description: "Scans a repository for compromised packages across all branches."
inputs:
  slack-webhook-url:
    description: "Slack Webhook URL for notifications"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Clone hof-vulnerabilities-scanner
      run: git clone https://github.com/UKHomeOfficeForms/hof-vulnerabilities-scanner.git
      shell: bash

    - name: Run vulnerability scan
      run: |
        set -euo pipefail
        git fetch --all --prune
        branches=$(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||')
        summary=""
        any_compromised=0
        repo_name=$(basename "$GITHUB_REPOSITORY")

        for br in $branches; do
          echo "=== Scanning branch: $br ==="
          git checkout --force -B "$br" "origin/$br"
          node hof-vulnerabilities-scanner/index.js --out "scan-results-${br}.json" || true
          cnt=$(jq '.vulnerabilitiesCount // 0' "scan-results-${br}.json" 2>/dev/null || echo 0)
          if [ "$cnt" -gt 0 ]; then
            any_compromised=1
            summary="${summary}${br}: ${cnt} compromised packages\n"
          else
            summary="${summary}${br}: 0\n"
          fi
        done

        if [ "$any_compromised" -eq 0 ]; then
          final="$repo_name: No compromised packages found. ✅"
        else
          final="$repo_name: Compromised packages found:\n${summary}. ❌"
        fi

        echo "summary=$final" >> $GITHUB_ENV
      shell: bash

    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        SCAN_OUTPUT: "[testing branch: refactoring-use-matrix] ${{ env.summary }}"
      run: |
        payload=$(jq -n --arg text "$SCAN_OUTPUT" '{text: $text}')
        curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
      shell: bash
